sot_controller:
  type: "sot_reem_controller/SotReemController"
  joints:
    - arm_left_1_joint
    - arm_left_2_joint
    - arm_left_3_joint
    - arm_left_4_joint
    - arm_left_5_joint
    - arm_left_6_joint
    - arm_left_7_joint
    - arm_right_1_joint
    - arm_right_2_joint
    - arm_right_3_joint
    - arm_right_4_joint
    - arm_right_5_joint
    - arm_right_6_joint
    - arm_right_7_joint
    - hand_left_index_1_joint
    - hand_left_index_2_joint
    - hand_left_index_3_joint
    - hand_left_middle_1_joint
    - hand_left_middle_2_joint
    - hand_left_middle_3_joint
    - hand_left_thumb_joint
    - hand_right_index_1_joint
    - hand_right_index_2_joint
    - hand_right_index_3_joint
    - hand_right_middle_1_joint
    - hand_right_middle_2_joint
    - hand_right_middle_3_joint
    - hand_right_thumb_joint
    - head_1_joint
    - head_2_joint
    - torso_1_joint
    - torso_2_joint
    - wheel_left_joint
    - wheel_right_joint
    - torso_base_joint
